tap "nicoverbruggen/cask"
tap "shivammathur/extensions"
tap "shivammathur/php"
# Plugin manager for zsh, inspired by antigen and antibody
brew "antidote"
# Official Amazon AWS command-line interface
brew "awscli"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Dependency manager for Cocoa projects
brew "cocoapods"
# Image format providing lossless and lossy compression for web images
brew "webp"
# General-purpose scripting language
brew "php"
# Dependency Manager for PHP
brew "composer"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Clean Docker containers, images, networks, and volumes
brew "docker-clean"
# Isolated development environments using Docker
brew "docker-compose"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Modern, maintained replacement for ls
brew "eza"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Firebase command-line tools
brew "firebase-cli"
# Distributed revision control system
brew "git"
# OpenGL and OpenGL ES reference compiler for shading languages
brew "glslang"
# Improved top (interactive process viewer)
brew "htop"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Manage your Java environment
brew "jenv"
# Simple terminal UI for git commands
brew "lazygit"
# Mac App Store command-line interface
brew "mas"
# Development kit for the Java programming language
brew "openjdk"
# Java-based project management
brew "maven"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"
# Libraries for security-enabled client and server applications
brew "nss"
# Development kit for the Java programming language
brew "openjdk@21"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Python version management
brew "pyenv"
# Python interface to Tcl/Tk
brew "python-tk@3.13"
# Static http server anywhere you need one
brew "serve"
# Autoformat shell script source code
brew "shfmt"
# Upgrade all the things
brew "topgrade"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Command-line interface for WordPress
brew "wp-cli"
# 3D creation suite
cask "blender"
# Web browser focusing on privacy
cask "brave-browser"
# Test localhost and staging websites
cask "browserstacklocal"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
cask "font-jetbrains-mono"
# GIT client
cask "fork"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "gcloud-cli"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Open source API development ecosystem
cask "hoppscotch"
# Menu bar manager
cask "jordanbaird-ice"
# File archiver
cask "keka"
# Blocks all Keyboard and TouchBar input
cask "keyboardcleantool"
# Discover, download, and run local LLMs
cask "lm-studio"
# Software for Logitech devices
cask "logi-options+"
# Controls and monitors all fans on Apple computers
cask "macs-fan-control"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Multi-platform web browser
cask "microsoft-edge"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Cloud storage client
cask "onedrive"
# Finder Toolbar app to open the current directory in Terminal or Editor
cask "openinterminal"
# Replacement for Docker Desktop
cask "orbstack"
# Utility to uninstall apps and remove leftover files from old/uninstalled apps
cask "pearcleaner"
cask "nicoverbruggen/cask/phpmon"
# Thumbnails, static previews, cover art and metadata for video files
cask "quicklook-video"
# Control your tools with a few keystrokes
cask "raycast"
# Screenshot measurement and annotation tool
cask "shottr"
# Graphical client for Git version control
cask "sourcetree"
# Music streaming service
cask "spotify"
# Messaging app with a focus on speed and security
cask "telegram"
# Batch rename utility
cask "transnomino"
# Virtual machines UI using QEMU
cask "utm"
# Open-source code editor
cask "visual-studio-code"
# Vietnamese input method engine
cask "xkey"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "CotEditor", id: 1024640650
mas "Folder Quick Look", id: 6753110395
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "uBlock Origin Lite", id: 6745342698
mas "Xcode", id: 497799835
