tap "alienator88/cask"
tap "buo/cask-upgrade"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/services"
tap "shivammathur/php"
tap "teamookla/speedtest"
# Image format providing lossless and lossy compression for web images
brew "webp"
# Official Amazon AWS command-line interface
brew "awscli"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Dependency manager for Cocoa projects
brew "cocoapods"
# General-purpose scripting language
brew "php"
# Dependency Manager for PHP
brew "composer"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Clean Docker containers, images, networks, and volumes
brew "docker-clean"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Modern, maintained replacement for ls
brew "eza"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# OpenGL and OpenGL ES reference compiler for shading languages
brew "glslang"
# Simple terminal UI for git commands
brew "lazygit"
# Keep your Mac's application settings in sync
brew "mackup"
# Mac App Store command-line interface
brew "mas"
# Fast Cross-Platform Package Manager
brew "micromamba"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"
# Libraries for security-enabled client and server applications
brew "nss"
# Manage multiple Node.js versions
brew "nvm"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Python version management
brew "pyenv"
# Static http server anywhere you need one
brew "serve"
# Cross-shell prompt for astronauts
brew "starship"
# JavaScript package manager
brew "yarn"
# Ookla Speedtest
brew "teamookla/speedtest/speedtest"
# Tools for building Android applications
cask "android-studio"
# Utility improving 3rd party mouse performance and functionalities
cask "bettermouse"
# 3D creation suite
cask "blender"
# Web browser focusing on privacy
cask "brave-browser"
# Vietnamese keyboard
cask "evkey"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-for-powerlevel10k"
cask "font-zed-mono"
cask "font-zed-sans"
# GIT client
cask "fork"
# Web browser
cask "google-chrome"
# Utility to hide menu bar items
cask "hiddenbar"
# Free and open-source media player
cask "iina"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Menu bar calendar
cask "itsycal"
# File archiver
cask "keka"
# Blocks all Keyboard and TouchBar input
cask "keyboardcleantool"
# Utility that shows the latest app updates
cask "latest"
# Discover, download, and run local LLMs
cask "lm-studio"
# Controls and monitors all fans on Apple computers
cask "macs-fan-control"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Minimal installer for conda
cask "miniconda"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# Finder Toolbar app to open the current directory in Terminal or Editor
cask "openinterminal"
# Replacement for Docker Desktop
cask "orbstack"
# Utility to uninstall apps and remove leftover files from old/uninstalled apps
cask "pearcleaner"
# Quick Look plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# Quick Look plugin to view patch files
cask "qlprettypatch"
# Quick Look plugin for plaintext files without an extension
cask "qlstephen"
# Thumbnails, static previews, cover art and metadata for video files
cask "qlvideo"
# Quick Look plugin for CSV files
cask "quicklook-csv"
# Quick Look plugin for JSON files
cask "quicklook-json"
# Control your tools with a few keystrokes
cask "raycast"
# MySQL/MariaDB database management
cask "sequel-ace"
# Screenshot measurement and annotation tool
cask "shottr"
# Video chat, voice call and instant messaging application
cask "skype"
# Graphical client for Git version control
cask "sourcetree"
# Utility to hide the notch
cask "topnotch"
# Open-source code editor
cask "visual-studio-code"
# Quick Look plugin for webp files
cask "webpquicklook"
mas "Bitwarden", id: 1352778147
mas "CotEditor", id: 1024640650
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "Tot", id: 1491071483
mas "Xcode", id: 497799835
